theme: jekyll-theme-tactile
title: David Jackson's Research Website
description: A central repository for information about my research, my blogs and any code I write as part of my work.
guthub_username: davidjackson-uk
